source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'capybara', '~> 3.24.0'
gem 'cucumber', '3.1.2'
gem 'fileutils', '~> 0.7.2'
gem 'multi_json', '~> 1.11', '>= 1.11.2'
gem 'pry', '~> 0.10'
gem 'require_all', '~> 2.0'
gem 'rspec', '~> 3.8'
gem 'selenium-webdriver', '~>3.142.3'
gem 'site_prism', '3.2'
